### ISSUE TITLE
Browser Width Bug - Upload Page

### ISSUE THREAD

**Issue by corebean** [zeroesapps/ladenfreude#14]
On Firefox when the browser has a width of 990 pixels to 1200 pixels the Upload Page looks weird. 

My preference is to keep the layout for Uploading as currently displayed on browser widths less than 990 pixels (ie single column - full width).

**Comment by bereczandor** [comment]
I have changed the layout to a bigger width because of the Crop preview canvas/image.
Secondly, if we go vertical with everything, the user needs to scroll too much to add data to the input fields. It was annoing just when i have tested the crop feature :)

But yes, i agree, there is room for optimization.
