### ISSUE TITLE
Mobile Upload / Post Creation

### ISSUE THREAD

**Issue by corebean** [zeroesapps/ladenfreude#24]
Testing from Safari on iOS on an old iPhone4S is not resulting in any success.
- Numbers are being ignored in the input field
- No post is being displayed after hitting "Post und Live setzen"

**Comment by russog** [comment]
Is it because it's not html5 capable?

Get Outlook for iOS




On Mon, Oct 17, 2016 at 7:18 PM +0100, "Corbin" <notifications@github.com> wrote:





Testing from Safari on iOS on an old iPhone4S is not resulting in any success.

- Numbers are being ignored in the input field
- No post is being displayed after hitting "Post und Live setzen"

--
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/zeroesapps/ladenfreude/issues/24

**Comment by corebean** [comment]
What, my phone?  I was able to upload posts from my mobile before hand...so
I am not sure what changed.

**Comment by bereczandor** [comment]
tested the upload on Mobile/Windows..seems to work.
